### ISSUE TITLE
ValheimPlus not loading, DLL keeps being deleted

### ISSUE THREAD

**Issue by shad-lp** [lloesche/valheim-server-docker#657]
Hello @lloesche and others,

I was still playing 3 three days ago, but today I can't play anymore.
When I connect to my server (after entering the password), I get a message saying "Incompatible version - The ValheimPlus mod must not be enabled"
Grantapher and pals tried to identify the problem, but it seems to be related to your last docker image.

My docker-compose file :

```
version: '2.1'
services:

   valheim-plus-server:
      image: lloesche/valheim-server
      container_name: valheim
      hostname: valheim
      networks:
         - net-proxy
         - net-notif
      cap_add:
         - CAP_SYS_NICE
      environment:
         # Configuration
         - PUID=1000
         - PGID=1000
         - SERVER_NAME=REDACTED
         - SERVER_PASS=REDACTED
         - SERVER_PORT=2456
         - WORLD_NAME=REDACTED
         - SERVER_PUBLIC=true
         - RESTART_CRON=45 5 * * *
         - RESTART_IF_IDLE=true
         - TZ=Europe/Brussels
         # Permitted IDs (Steam ID)
         - PERMITTEDLIST_IDS=REDACTED
         # Admin IDs (Steam ID)
         - ADMINLIST_IDS=REDACTED
         # Update configuration
         - UPDATE_CRON=30 6 * * *
         - UPDATE_IF_IDLE=true
         # Backups configuration
         - BACKUPS=true
         - BACKUPS_CRON=10 */6 * * *
         - BACKUPS_DIRECTORY=/config/backups
         - BACKUPS_MAX_AGE=5
         - BACKUPS_MAX_COUNT=25
         - BACKUPS_IF_IDLE=false
         - PERMISSIONS_UMASK=022
         # Status
         - STATUS_HTTP=true
         # Supervisord
         - SUPERVISOR_HTTP=true
         - SUPERVISOR_HTTP_PORT=9001
         # Discord
         - DISCORD_WEBHOOK=https://discord.com/api/webhooks/REDACTED
         ## Bootstrap
         - 'PRE_BOOTSTRAP_HOOK=curl -X POST -d "tag=botValheim&body=Server starting up..." http://apprise-api:8000/notify/apprise'
         ## Listening
         - 'POST_SERVER_LISTENING_HOOK=curl -X POST -d "tag=botValheim&body=Server __READY__..." http://apprise-api:8000/notify/apprise' 
         ## Shutdown
         - 'PRE_SERVER_SHUTDOWN_HOOK=curl -X POST -d "tag=botValheim&body=Shutting down server..." http://apprise-api:8000/notify/apprise'
         ## Restarting
         - 'PRE_RESTART_HOOK=curl -X POST -d "tag=botValheim&body=Restarting server..." http://apprise-api:8000/notify/apprise'
         # Mods
         - VALHEIM_PLUS=true
         - VALHEIM_PLUS_RELEASE=latest
         - VALHEIM_PLUS_REPO=Grantapher/ValheimPlus
         - VPCFG_AdvancedBuildingMode_enabled=true
         - VPCFG_AdvancedEditingMode_enabled=true
         - VPCFG_Building_enabled=true
         - VPCFG_Building_enableAreaRepair=true
         - VPCFG_Camera_enabled=true
         - VPCFG_Camera_cameraFOV=65
         - VPCFG_Chat_enabled=true
         - VPCFG_Chat_outOfRangeShoutsDisplayInChatWindow=true
         - VPCFG_Chat_defaultNormalDistance=7500
         - VPCFG_FireSource_enabled=true
         - VPCFG_FireSource_torches=true
         - VPCFG_FireSource_fires=true
         - VPCFG_Game_enabled=true
         - VPCFG_Game_bigPortalNames=true
         - VPCFG_Hud_enabled
         - VPCFG_Hud_showRequiredItems=true
         - VPCFG_Hud_experienceGainedNotifications=true
         - VPCFG_Hud_displayBowAmmoCounts=2
         - VPCFG_Map_enabled=true
         - VPCFG_Map_shareMapProgression=true
         - VPCFG_Map_preventPlayerFromTurningOffPublicPosition=true
         - VPCFG_Map_shareAllPins=true
         - VPCFG_Map_displayCartsAndBoats=true
         - VPCFG_GridAlignment_enabled=true
         - VPCFG_Items_enabled=true
         - VPCFG_Items_noTeleportPrevention=true      
         # In case of broken update
         #- STEAMCMD_ARGS=-beta default_old
      ports:
         - 2456-2457:2456-2457/udp
         # if not in net-proxy network
         #- 9001:9001/tcp
      volumes:
         - /opt/valheim-live/config:/config
         - /opt/valheim-live/data:/opt/valheim
      labels:
         # watchtower label only monitoring
         - 'com.centurylinklabs.watchtower.enable=true'
      restart: unless-stopped
      
networks:

   net-proxy:
      external: true
      
   net-notif:
      external: true
```

My server's LogOutput.log file :

```
[Message:   BepInEx] BepInEx 5.4.22.0 - valheim_server (11/8/2023 6:30:19 AM)
[Message:   BepInEx] User is running BepInExPack Valheim version 5.4.2202 from Thunderstore
[Info   :   BepInEx] Running under Unity vUnknown (post-2017)
[Info   :   BepInEx] CLR runtime version: 4.0.30319.42000
[Info   :   BepInEx] Supports SRE: True
[Info   :   BepInEx] System platform: Bits64, Linux
[Message:   BepInEx] Preloader started
[Info   :   BepInEx] Loaded 1 patcher method from [BepInEx.Preloader 5.4.22.0]
[Info   :   BepInEx] 1 patcher plugin loaded
[Info   :   BepInEx] Patching [UnityEngine.CoreModule] with [BepInEx.Chainloader]
[Message:   BepInEx] Preloader finished
[Info   :   BepInEx] Detected Unity version: v2022.3.12f1
[Message:   BepInEx] Chainloader ready
[Message:   BepInEx] Chainloader started
[Info   :   BepInEx] 0 plugins to load
[Message:   BepInEx] Chainloader startup complete
[Warning: Unity Log] 02/07/2024 23:48:43: Fetching PlatformPrefs 'GuiScale' before loading defaults

[Warning: Unity Log] 02/07/2024 23:48:43: Fetching PlatformPrefs 'GuiScale' before loading defaults

[Warning: Unity Log] Privilege Multiplayer is not known on this platform. Privilege therefore is granted without check...
[Warning: Unity Log] Privilege UserGeneratedContent is not known on this platform. Privilege therefore is granted without check...
[Warning: Unity Log] Privilege CrossPlay is not known on this platform. Privilege therefore is granted without check...
[Info   : Unity Log] 02/07/2024 23:48:43: Starting to load scene:start

[Warning: Unity Log] No mesh data available for mesh default on particle system Legs. Make sure Read/Write Enabled is set in the importer to work on the particle system renderer
[Warning: Unity Log] No mesh data available for mesh default on particle system BodyGibs (2). Make sure Read/Write Enabled is set in the importer to work on the particle system renderer
[Warning: Unity Log] No mesh data available for mesh default on particle system vfx_Firework_Rocket_Blue. Make sure Read/Write Enabled is set in the importer to work on the particle system renderer
[Warning: Unity Log] No mesh data available for mesh default on particle system vfx_Firework_Rocket_Yellow. Make sure Read/Write Enabled is set in the importer to work on the particle system renderer
[Warning: Unity Log] No mesh data available for mesh default on particle system Wings. Make sure Read/Write Enabled is set in the importer to work on the particle system renderer
[Warning: Unity Log] No mesh data available for mesh default on particle system shockwave_plane. Make sure Read/Write Enabled is set in the importer to work on the particle system renderer
[Warning: Unity Log] No mesh data available for mesh default on particle system Carapace. Make sure Read/Write Enabled is set in the importer to work on the particle system renderer
[Warning: Unity Log] No mesh data available for mesh default on particle system Carapace_ass. Make sure Read/Write Enabled is set in the importer to work on the particle system renderer
[Warning: Unity Log] No mesh data available for mesh default on particle system eyes. Make sure Read/Write Enabled is set in the importer to work on the particle system renderer
[Warning: Unity Log] No mesh data available for mesh default on particle system vfx_RockHit (2). Make sure Read/Write Enabled is set in the importer to work on the particle system renderer
[Warning: Unity Log] No mesh data available for mesh default on particle system Legs. Make sure Read/Write Enabled is set in the importer to work on the particle system renderer
[Warning: Unity Log] No mesh data available for mesh default on particle system Carapace. Make sure Read/Write Enabled is set in the importer to work on the particle system renderer
[Warning: Unity Log] No mesh data available for mesh default on particle system vfx_RockHit (2). Make sure Read/Write Enabled is set in the importer to work on the particle system renderer
[Warning: Unity Log] No mesh data available for mesh default on particle system Carapace. Make sure Read/Write Enabled is set in the importer to work on the particle system renderer
[Warning: Unity Log] No mesh data available for mesh default on particle system BodyGibs. Make sure Read/Write Enabled is set in the importer to work on the particle system renderer
[Warning: Unity Log] No mesh data available for mesh default on particle system Legs. Make sure Read/Write Enabled is set in the importer to work on the particle system renderer
[Warning: Unity Log] No mesh data available for mesh default on particle system Legs. Make sure Read/Write Enabled is set in the importer to work on the particle system renderer
[Warning: Unity Log] No mesh data available for mesh default on particle system vfx_Firework_Rocket. Make sure Read/Write Enabled is set in the importer to work on the particle system renderer
[Warning: Unity Log] No mesh data available for mesh default on particle system vfx_Firework_Rocket_Purple. Make sure Read/Write Enabled is set in the importer to work on the particle system renderer
[Warning: Unity Log] No mesh data available for mesh default on particle system Head. Make sure Read/Write Enabled is set in the importer to work on the particle system renderer
[Warning: Unity Log] No mesh data available for mesh default on particle system Carapace_ass. Make sure Read/Write Enabled is set in the importer to work on the particle system renderer
[Warning: Unity Log] No mesh data available for mesh default on particle system vfx_Firework_Rocket_Cyan. Make sure Read/Write Enabled is set in the importer to work on the particle system renderer
[Warning: Unity Log] No mesh data available for mesh default on particle system Wings. Make sure Read/Write Enabled is set in the importer to work on the particle system renderer
[Warning: Unity Log] No mesh data available for mesh default on particle system Carapace. Make sure Read/Write Enabled is set in the importer to work on the particle system renderer
[Warning: Unity Log] No mesh data available for mesh default on particle system Wings. Make sure Read/Write Enabled is set in the importer to work on the particle system renderer
[Warning: Unity Log] No mesh data available for mesh default on particle system vfx_Firework_Rocket_Red. Make sure Read/Write Enabled is set in the importer to work on the particle system renderer
[Warning: Unity Log] No mesh data available for mesh default on particle system Eggs. Make sure Read/Write Enabled is set in the importer to work on the particle system renderer
[Warning: Unity Log] No mesh data available for mesh default on particle system BodyGibs (1). Make sure Read/Write Enabled is set in the importer to work on the particle system renderer
[Warning: Unity Log] No mesh data available for mesh default on particle system Carapace. Make sure Read/Write Enabled is set in the importer to work on the particle system renderer
[Warning: Unity Log] No mesh data available for mesh default on particle system vfx_Firework_Rocket_Green. Make sure Read/Write Enabled is set in the importer to work on the particle system renderer
[Warning: Unity Log] Only custom filters can be played. Please add a custom filter or an audioclip to the audiosource (Amb_MainMenu).
[Warning: Unity Log] HDR Render Texture not supported, disabling HDR on reflection probe.
[Info   : Unity Log] 02/07/2024 23:48:47: Get create world NoRulez

[Info   : Unity Log] 02/07/2024 23:48:47: Using environment steamid 892970

[Info   : Unity Log] 02/07/2024 23:48:47: Using steam APPID:892970

[Info   : Unity Log] 02/07/2024 23:48:47: Server ID 900719925XXXXXXXX

[Info   : Unity Log] 02/07/2024 23:48:47: Authentication:k_ESteamNetworkingAvailability_Waiting

[Info   : Unity Log] 02/07/2024 23:48:47: Steam game server initialized

[Info   : Unity Log] 02/07/2024 23:48:47: Using default prefs

[Info   : Unity Log] 02/07/2024 23:48:47: Valheim version: l-0.217.38 (network version 20)

[Info   : Unity Log] Trying to set graphic mode to 'Custom'
[Info   : Unity Log] Graphic mode 'Custom' is not or no longer supported. Fallback to default mode for platform...
[Info   : Unity Log] Graphic mode 'Custom' applied!
[Info   : Unity Log] 02/07/2024 23:48:48: Worldgenerator version setup:2

[Info   : Unity Log] 02/07/2024 23:48:48: Console: Valheim l-0.217.38 (network version 20)

[Info   : Unity Log] 02/07/2024 23:48:48: Console: 

[Info   : Unity Log] 02/07/2024 23:48:48: Console: type "help" - for commands

[Info   : Unity Log] 02/07/2024 23:48:48: Console: 

[Info   : Unity Log] 02/07/2024 23:48:48: Render threading mode:SingleThreaded

[Warning: Unity Log] 02/07/2024 23:48:48: Set button "CamZoomIn" to None!

[Warning: Unity Log] 02/07/2024 23:48:48: Set button "CamZoomOut" to None!

[Warning: Unity Log] 02/07/2024 23:48:48: Set button "CamZoomIn" to None!

[Warning: Unity Log] 02/07/2024 23:48:48: Set button "CamZoomOut" to None!

[Warning: Unity Log] 02/07/2024 23:48:48: Missing audio clip in music respawn

[Info   : Unity Log] 02/07/2024 23:48:48: Loaded localization file #0 - 'localization' language: 'English'

[Info   : Unity Log] 02/07/2024 23:48:48: Loaded localization file #1 - 'localization_extra' language: 'English'

[Info   : Unity Log] 02/07/2024 23:48:48: Loaded localization file #2 - 'heightmap_message' language: 'English'

[Info   : Unity Log] 02/07/2024 23:48:48: Loaded localization file #3 - 'localization_hildir' language: 'English'

[Info   : Unity Log] 02/07/2024 23:48:48: Loaded localization file #4 - 'localization_emotes' language: 'English'

[Info   : Unity Log] 02/07/2024 23:48:48: Sending PlayFab login request (attempt 1)

[Info   : Unity Log] 02/07/2024 23:48:48: Login postponed until ID has been set.

[Info   : Unity Log] The shader Hidden/Dof/DepthOfFieldHdr (UnityEngine.Shader) on effect Main Camera (UnityStandardAssets.ImageEffects.DepthOfField) is not supported on this platform!
[Warning: Unity Log] The image effect Main Camera (UnityStandardAssets.ImageEffects.DepthOfField) has been disabled as it's not supported on the current platform.
[Info   : Unity Log] The shader Hidden/SunShaftsComposite (UnityEngine.Shader) on effect Main Camera (UnityStandardAssets.ImageEffects.SunShafts) is not supported on this platform!
[Info   : Unity Log] The shader Hidden/SimpleClear (UnityEngine.Shader) on effect Main Camera (UnityStandardAssets.ImageEffects.SunShafts) is not supported on this platform!
[Warning: Unity Log] The image effect Main Camera (UnityStandardAssets.ImageEffects.SunShafts) has been disabled as it's not supported on the current platform.
[Info   : Unity Log] 02/07/2024 23:48:48: Starting music menu

[Error  : Unity Log] There is no texture data available to upload.
[Warning: Unity Log] HDR Render Texture not supported, disabling HDR on reflection probe.
[Warning: Unity Log] HDR Render Texture not supported, disabling HDR on reflection probe.
[Info   : Unity Log] 02/07/2024 23:48:48: Using default prefs

[Info   : Unity Log] 02/07/2024 23:48:48: Console: Valheim l-0.217.38 (network version 20)

[Info   : Unity Log] 02/07/2024 23:48:48: Console: 

[Info   : Unity Log] 02/07/2024 23:48:48: Console: type "help" - for commands

[Info   : Unity Log] 02/07/2024 23:48:48: Console: 

[Info   : Unity Log] 02/07/2024 23:48:48: isModded: False

[Info   : Unity Log] 02/07/2024 23:48:48: Zonesystem Awake 199648

[Info   : Unity Log] 02/07/2024 23:48:48: DungeonDB Awake 199648

[Info   : Unity Log] 02/07/2024 23:48:48: Registering lobby

[Info   : Unity Log] 02/07/2024 23:48:48: Worldgenerator version setup:1

[Info   : Unity Log] 02/07/2024 23:48:51: Audioman already exist, destroying self

[Info   : Unity Log] 02/07/2024 23:48:51: Console: /w [text] - Whisper

[Info   : Unity Log] 02/07/2024 23:48:51: Console: /s [text] - Shout

[Info   : Unity Log] 02/07/2024 23:48:51: Console: /die - Kill yourself

[Info   : Unity Log] 02/07/2024 23:48:51: Console: /resetspawn - Reset spawn point

[Info   : Unity Log] 02/07/2024 23:48:51: Console: /[emote]

[Info   : Unity Log] 02/07/2024 23:48:51: Console: Emotes: wave, sit, challenge, cheer, nonono, thumbsup, point, blowkiss, bow, cower, cry, despair, flex, comehere, headbang, kneel, laugh, roar, shrug, dance

[Info   : Unity Log] 02/07/2024 23:48:51: Console: 

[Error  : Unity Log] There is no texture data available to upload.
[Error  : Unity Log] There is no texture data available to upload.
[Error  : Unity Log] There is no texture data available to upload.
[Error  : Unity Log] There is no texture data available to upload.
[Error  : Unity Log] There is no texture data available to upload.
[Error  : Unity Log] There is no texture data available to upload.
[Error  : Unity Log] There is no texture data available to upload.
[Error  : Unity Log] There is no texture data available to upload.
[Error  : Unity Log] There is no texture data available to upload.
[Info   : Unity Log] 02/07/2024 23:48:55: Zonesystem Start 199648

[Info   : Unity Log] 02/07/2024 23:48:56: Added 3 locations, 0 vegetations, 0 environments, 0 biome env-setups, 0 clutter  from locations_cp1

[Info   : Unity Log] 02/07/2024 23:48:56: Added 1 locations, 0 vegetations, 2 environments, 0 biome env-setups, 0 clutter  from locations_mountaincaves

[Info   : Unity Log] 02/07/2024 23:48:56: Added 27 locations, 25 vegetations, 5 environments, 1 biome env-setups, 3 clutter  from locations_mistlands

[Info   : Unity Log] 02/07/2024 23:48:56: Added 4 locations, 0 vegetations, 1 environments, 0 biome env-setups, 0 clutter  from locations_hildir

[Info   : Unity Log] 02/07/2024 23:48:56: DungeonDB Start 199648

[Info   : Unity Log] 02/07/2024 23:48:56: ZRpc timeout set to 30s 

[Info   : Unity Log] 02/07/2024 23:48:56: ZNET START

[Info   : Unity Log] 02/07/2024 23:48:56: Load world: NoRulez (NoRulez)

[Info   : Unity Log] 02/07/2024 23:48:56: Loading 1838825 zdos, my sessionID: 1254713861, data version: 33

[Info   : Unity Log] 02/07/2024 23:48:56: Creating ZDOs

[Info   : Unity Log] 02/07/2024 23:48:57: Loading in ZDOs

[Info   : Unity Log] 02/07/2024 23:49:00: Adding to Dictionary

[Info   : Unity Log] 02/07/2024 23:49:00: Adding to Sectors

[Info   : Unity Log] 02/07/2024 23:49:01: Connecting Portals, Spawners & ZSyncTransforms

[Info   : Unity Log] ConnectPortals => Connected 36 portals.
[Info   : Unity Log] ConnectSpawners => Connected 2346 spawners and 3772 'done' spawners.
[Info   : Unity Log] 02/07/2024 23:49:01: Loaded 9850 locations

[Info   : Unity Log] 02/07/2024 23:49:01: Unloading unused assets

[Info   : Unity Log] The shader Hidden/Dof/DepthOfFieldHdr (UnityEngine.Shader) on effect Main Camera (UnityStandardAssets.ImageEffects.DepthOfField) is not supported on this platform!
[Warning: Unity Log] The image effect Main Camera (UnityStandardAssets.ImageEffects.DepthOfField) has been disabled as it's not supported on the current platform.
[Info   : Unity Log] The shader Hidden/SunShaftsComposite (UnityEngine.Shader) on effect Main Camera (UnityStandardAssets.ImageEffects.SunShafts) is not supported on this platform!
[Info   : Unity Log] The shader Hidden/SimpleClear (UnityEngine.Shader) on effect Main Camera (UnityStandardAssets.ImageEffects.SunShafts) is not supported on this platform!
[Warning: Unity Log] The image effect Main Camera (UnityStandardAssets.ImageEffects.SunShafts) has been disabled as it's not supported on the current platform.
[Info   : Unity Log] 02/07/2024 23:49:02: Game server connected

[Info   : Unity Log] 02/07/2024 23:50:45: Got status changed msg k_ESteamNetworkingConnectionState_Connecting

[Info   : Unity Log] 02/07/2024 23:50:45: New connection

[Info   : Unity Log] 02/07/2024 23:50:45: Accepting connection k_EResultOK

[Info   : Unity Log] 02/07/2024 23:50:45: Connecting to Steamworks.SteamNetworkingIdentity

[Info   : Unity Log] 02/07/2024 23:50:45: Got status changed msg k_ESteamNetworkingConnectionState_Connected

[Info   : Unity Log] 02/07/2024 23:50:45: Connected

[Info   : Unity Log] 02/07/2024 23:50:45: Got connection SteamID 765611979XXXXXXXX

[Info   : Unity Log] 02/07/2024 23:50:45: Got handshake from client 765611979XXXXXXXX

[Info   : Unity Log] 02/07/2024 23:50:49: Network version check, their:20, mine:20

[Info   : Unity Log] 02/07/2024 23:50:49: Server: New peer connected,sending global keys

[Info   : Unity Log] 02/07/2024 23:50:51: RPC_Disconnect

[Info   : Unity Log] 02/07/2024 23:50:51: Disposing socket

[Info   : Unity Log] 02/07/2024 23:50:51: Closing socket 765611979XXXXXXXX

[Info   : Unity Log] 02/07/2024 23:50:51:   send queue size:0

[Info   : Unity Log] 02/07/2024 23:50:51: Disposing socket

[Info   : Unity Log] 02/07/2024 23:50:51: Got status changed msg k_ESteamNetworkingConnectionState_ClosedByPeer

[Info   : Unity Log] 02/07/2024 23:50:51: Socket closed by peer Steamworks.SteamNetConnectionStatusChangedCallback_t

[Info   : Unity Log] 02/07/2024 23:50:51: Got status changed msg k_ESteamNetworkingConnectionState_None

[Info   : Unity Log] 02/07/2024 23:51:24: Game - OnApplicationQuit

[Info   : Unity Log] 02/07/2024 23:51:24: Shuting down

[Info   : Unity Log] 02/07/2024 23:51:24: ZNet Shutdown

[Info   : Unity Log] 02/07/2024 23:51:24: PrepareSave: clone done in 317ms

[Info   : Unity Log] 02/07/2024 23:51:25: PrepareSave: ZDOExtraData.PrepareSave done in 440 ms

[Info   : Unity Log] 02/07/2024 23:51:31: Unloading unused assets

[Info   : Unity Log] 02/07/2024 23:51:31: Sending disconnect msg

[Info   : Unity Log] ZPlayFabMatchmaking::UnregisterServer - unregistering server now. State: Uninitialized
[Info   : Unity Log] 02/07/2024 23:51:31: Disposing socket

[Info   : Unity Log] 02/07/2024 23:51:31: Stopping listening socket

[Info   : Unity Log] 02/07/2024 23:51:31: Last socket, unregistering callback

[Info   : Unity Log] 02/07/2024 23:51:31: ZSteamSocket  UnregisterGlobalCallbacks, existing sockets:0

[Info   : Unity Log] 02/07/2024 23:51:31: Stopping build thread
```

AFAIK, I should have at least 1 plugin loaded : `[Info   :   BepInEx] 0 plugins to load`

What I tried so far :
- putting manually the ValheimPlus.dll file in /opt/valheim/data/plus/BepInEx/plugins, restart the server, the file is deleted (it's even logged)
- deleting the cached version, therefore the specified release is downloaded upon reboot, but that does not work better, at least I can tell that this is not related to a github rate limit
- changing the puid/pgid in case of missing permissions

Any help appreciated !

**Comment by lloesche** [comment]
Hey @shad-lp, thank you for the report. Let me look into it. We recently added a `--delete` flag to the sync of the plugins folder. I suspect you're running into some side-effect of that change.

**Comment by lloesche** [comment]
I can reproduce the issue you are seeing and it is caused by the "unused plugin cleanup" PR I merged two days ago. I will revert the change until we can find a properly working solution.

Sorry about the inconvenience, I should have tested the PR better before merging!

**Comment by shad-lp** [comment]
Thanks a lot for your quick answer. I was still not able to connect to my server with V+ enabled. I ended up specifying the tag version in the VALHEIM_PLUS_RELEASE env var, "tags/0.9.12.0" instead of "latest", and now I can connect.
That's some strange behaviour because the latest Grantapher release is the the 0.9.12.0 version. I made my report to V+ already to see how they interpret this too.

**Comment by Shawak** [comment]
docker tags e.g. "latest" are cached locally, you have to run something amoung `docker image rm <image>:latest` before it resolves correctly again. It's always better to use specific versions instead of `latest`.

**Comment by shad-lp** [comment]
> Docker tags e.g. "latest" are cached locally, you have to run something among `docker image rm <image>:latest` before it resolves correctly again. It's always better to use specific versions instead of `latest`.

The problem was not the docker image tag, but the env var value related to the last release of V+
